name: sqlite_viewer2
description: A Flutter package provides a widget to display the contents of SQLite.
version: 2.0.0
homepage: https://blog.fragment.co.jp/

sqlite_viewer:
  git:
    url: https://github.com/kofj/flutter-sqlite-viewer2.git

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_table: ^2.0.1
  path: ^1.9.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
